(()=>{
let ctx=null,timer=null,running=false,nextTime=0,eventIndex=0;
const BPM=172,QUARTER=60/BPM,EIGHTH=QUARTER/2,AC=window.AudioContext||window.webkitAudioContext;
const SEMI={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,F:5,'F#':6,Gb:6,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11};
let master=null,comp=null;
function audio(){if(!ctx){ctx=new AC();master=ctx.createGain();master.gain.value=.46;comp=ctx.createDynamicsCompressor();comp.threshold.value=-15;comp.knee.value=12;comp.ratio.value=7;comp.attack.value=.002;comp.release.value=.16;master.connect(comp).connect(ctx.destination)}if(ctx.state==='suspended')ctx.resume();return ctx}
function hz(note){const m=note.match(/^([A-G])([#b]?)(\d)$/),key=m[1]+m[2],oct=+m[3],midi=12*(oct+1)+SEMI[key];return 440*Math.pow(2,(midi-69)/12)}
function gainEnv(t,a,d,v,dest){const c=audio(),g=c.createGain();g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(v,.0002),t+a);g.gain.exponentialRampToValueAtTime(.0001,t+a+d);g.connect(dest||master);return g}
function wave(note,t,dur,type,vol,oct=1,det=0,cut=5000,dest=null){const c=audio(),o=c.createOscillator(),lp=c.createBiquadFilter(),g=gainEnv(t,.004,dur,vol,dest||master);o.type=type;o.frequency.value=hz(note)*oct;o.detune.value=det;lp.type='lowpass';lp.frequency.value=cut;o.connect(lp).connect(g);o.start(t);o.stop(t+dur+.04)}
function kick(t,strong=1){const c=audio(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(145,t);o.frequency.exponentialRampToValueAtTime(43,t+.075);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.58*strong,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+.21);o.connect(g).connect(master);o.start(t);o.stop(t+.23);const len=Math.floor(c.sampleRate*.024),b=c.createBuffer(1,len,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*(1-i/len);const s=c.createBufferSource(),bp=c.createBiquadFilter(),cg=c.createGain();s.buffer=b;bp.type='bandpass';bp.frequency.value=1700;bp.Q.value=.8;cg.gain.value=.05*strong;s.connect(bp).connect(cg).connect(master);s.start(t)}
function bass(note,t,strong=1){wave(note,t,.26,'sine',.42*strong,1,0,280);wave(note,t,.20,'triangle',.17*strong,2,-5,680);wave(note,t,.12,'square',.040*strong,2,3,980);wave(note,t,.15,'sine',.10*strong,.5,0,180)}
function chank(t,strong=1){const c=audio(),len=Math.floor(c.sampleRate*.055),b=c.createBuffer(1,len,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*Math.exp(-i/(len*.14));const s=c.createBufferSource(),bp=c.createBiquadFilter(),hp=c.createBiquadFilter(),g=c.createGain();s.buffer=b;bp.type='bandpass';bp.frequency.value=1550;bp.Q.value=1.4;hp.type='highpass';hp.frequency.value=650;g.gain.value=.12*strong;s.connect(bp).connect(hp).connect(g).connect(master);s.start(t)}
function brassLead(note,t,units,accent=1){const c=audio(),dur=Math.max(.08,units*EIGHTH*.90),f=hz(note),bus=c.createGain(),hp=c.createBiquadFilter(),lp=c.createBiquadFilter(),comp2=c.createDynamicsCompressor();hp.type='highpass';hp.frequency.value=120;lp.type='lowpass';lp.frequency.value=2400;lp.Q.value=.8;comp2.threshold.value=-20;comp2.ratio.value=3.5;comp2.attack.value=.004;comp2.release.value=.10;bus.connect(hp).connect(lp).connect(comp2).connect(master);const g=c.createGain();g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.060*accent,t+.018);g.gain.exponentialRampToValueAtTime(.048*accent,t+dur*.55);g.gain.exponentialRampToValueAtTime(.0001,t+dur);const form1=c.createBiquadFilter(),form2=c.createBiquadFilter(),form3=c.createBiquadFilter();form1.type='bandpass';form1.frequency.value=520;form1.Q.value=2;form2.type='bandpass';form2.frequency.value=1050;form2.Q.value=2.6;form3.type='bandpass';form3.frequency.value=1850;form3.Q.value=3.2;const mix=c.createGain();mix.gain.value=.75;[['sawtooth',f,-8,.60],['sawtooth',f,7,.45],['square',f*.5,2,.22],['triangle',f*2,-3,.20]].forEach(([type,fr,det,vol])=>{const o=c.createOscillator(),og=c.createGain();o.type=type;o.frequency.value=fr;o.detune.value=det;og.gain.value=vol;o.connect(og).connect(mix);o.start(t);o.stop(t+dur+.04)});mix.connect(form1);mix.connect(form2);mix.connect(form3);const sum=c.createGain();form1.connect(sum);form2.connect(sum);form3.connect(sum);sum.connect(g).connect(bus)}
function tromboneDouble(note,t,units,accent=1){const c=audio(),dur=Math.max(.08,units*EIGHTH*.86),f=hz(note)*.5,o1=c.createOscillator(),o2=c.createOscillator(),lp=c.createBiquadFilter(),g=c.createGain();o1.type='sawtooth';o2.type='triangle';o1.frequency.value=f;o2.frequency.value=f;o2.detune.value=6;lp.type='lowpass';lp.frequency.value=1450;lp.Q.value=.7;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.022*accent,t+.020);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o1.connect(lp);o2.connect(lp);lp.connect(g).connect(master);o1.start(t);o2.start(t);o1.stop(t+dur+.03);o2.stop(t+dur+.03)}
const A=[['A4',1.5],['D5',.5],['D5',1],['E5',1],['F5',1],['D5',1],['D5',1],['F5',1],['E5',1],['C5',1],['C5',1],['E5',1],['F5',.5],['E5',.5],['D5',.5],['C5',.5],['D5',1],['A4',1],['D5',1.5],['D5',.5],['D5',1],['E5',1],['F5',1],['D5',1],['D5',2],['G5',.5],['A5',.5],['G5',.5],['F5',.5],['E5',1],['D5',1],['F5',1],['D5',1],['D5',2]];
const B=[['A5',1],['A5',1],['G5',1],['F5',1],['E5',1],['C5',1],['C5',1],['E5',1],['G5',1],['G5',1],['F5',1],['E5',1],['F5',1],['D5',1],['D5',1],['F5',1],['A5',1],['A5',1],['G5',1],['F5',1],['E5',1],['C5',1],['C5',1],['E5',1],['G5',1],['G5',1],['F5',1],['E5',1],['F5',1],['D5',1],['D5',2]];
const C=A.slice();
const D=[['A5',1.5],['F5',.5],['F5',1],['A5',1],['G5',1],['E5',1],['E5',1],['F5',1],['G5',.5],['A5',.5],['G5',.5],['F5',.5],['E5',1],['D5',1],['D5',1],['E5',1],['F5',1],['G5',1],['A5',1.5],['F5',.5],['F5',1],['A5',1],['G5',1],['E5',1],['E5',1],['F5',1],['G5',.5],['A5',.5],['G5',.5],['F5',.5],['E5',1],['D5',1],['F5',1],['D5',1],['D5',2]];
const repeat=s=>s.concat(s),melody=[...repeat(A),...repeat(B),...repeat(C),...repeat(D)],progression=['D2','D2','C2','D2','D2','D2','A2','D2','D2','C2','C2','D2','D2','C2','A2','D2'];let totalUnits=0;const events=melody.map(x=>{const e={note:x[0],units:x[1],start:totalUnits};totalUnits+=x[1];return e});
function hat(t,open=false,vol=1){const c=audio(),len=Math.floor(c.sampleRate*(open?.085:.035)),b=c.createBuffer(1,len,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/len,open?.9:2.2);const s=c.createBufferSource(),hp=c.createBiquadFilter(),bp=c.createBiquadFilter(),g=c.createGain();s.buffer=b;hp.type='highpass';hp.frequency.value=5200;bp.type='bandpass';bp.frequency.value=open?8600:7400;bp.Q.value=.7;g.gain.value=(open?.032:.020)*vol;s.connect(hp).connect(bp).connect(g).connect(master);s.start(t)}
function snare(t,vol=1){const c=audio(),len=Math.floor(c.sampleRate*.095),b=c.createBuffer(1,len,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*Math.exp(-i/(len*.20));const s=c.createBufferSource(),bp=c.createBiquadFilter(),g=c.createGain();s.buffer=b;bp.type='bandpass';bp.frequency.value=1900;bp.Q.value=.85;g.gain.value=.060*vol;s.connect(bp).connect(g).connect(master);s.start(t);wave('D3',t,.06,'triangle',.018*vol,1,0,1200)}
function tamb(t,vol=1){const c=audio(),len=Math.floor(c.sampleRate*.11),b=c.createBuffer(1,len,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*Math.exp(-i/(len*.28));const s=c.createBufferSource(),hp=c.createBiquadFilter(),g=c.createGain();s.buffer=b;hp.type='highpass';hp.frequency.value=6500;g.gain.value=.020*vol;s.connect(hp).connect(g).connect(master);s.start(t)}
function pseudoFemaleVowel(note,t,dur=.22,vowel='a',vol=.030){const c=audio(),f=hz(note),bus=c.createGain(),g=c.createGain();g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+dur);const formants=vowel==='i'?[[300,4.5],[2300,7],[3000,8]]:vowel==='u'?[[350,4.5],[900,5],[2200,7]]:[[800,5],[1150,5],[2900,8]];for(let k=0;k<3;k++){const o=c.createOscillator();o.type=k===0?'sawtooth':'triangle';o.frequency.value=f*(k+1);o.detune.value=(k-1)*5;o.connect(bus);o.start(t);o.stop(t+dur+.03)}let node=bus;formants.forEach(([fq,q],idx)=>{const bp=c.createBiquadFilter();bp.type='bandpass';bp.frequency.value=fq;bp.Q.value=q;if(idx===0){node.connect(bp);node=bp}else{const split=c.createGain();bus.connect(split);split.connect(bp);bp.connect(g)}});node.connect(g).connect(master)}
function accompanimentAt(unit,t){const eighth=Math.floor(unit+.0001),pos=eighth%4,bar=Math.floor(eighth/4),root=progression[bar%progression.length];if(pos===0){kick(t,1.38);bass(root,t,1.42)}if(pos===2){kick(t,1.24);bass(root,t,1.30)}if(pos===1){chank(t,1.28);snare(t,.48)}if(pos===3){chank(t,1.42);snare(t,.58)}hat(t,false,pos===0||pos===2?.72:.90);if(pos===3&&bar%2===1)tamb(t,.90);if(pos===0&&bar%4===1)pseudoFemaleVowel('A4',t,.24,'a',.010);if(pos===0&&bar%4===3)pseudoFemaleVowel('D5',t,.26,'i',.010)}
let accUnit=0;function resetSchedule(){nextTime=audio().currentTime+.06;eventIndex=0;accUnit=0}function pump(){if(!running)return;const c=audio(),horizon=c.currentTime+.18;while(nextTime<horizon){if(eventIndex>=events.length){eventIndex=0;accUnit=0}const ev=events[eventIndex];while(accUnit<=ev.start+.0001){const t=nextTime+(accUnit-ev.start)*EIGHTH;if(t>=c.currentTime-.02)accompanimentAt(accUnit,t);accUnit++}brassLead(ev.note,nextTime,ev.units,(eventIndex%16===0)?1.08:1);if(eventIndex%4===0)tromboneDouble(ev.note,nextTime,ev.units,.85);nextTime+=ev.units*EIGHTH;eventIndex++;if(eventIndex>=events.length)accUnit=0}}
function start(){audio();if(running)return;running=true;resetSchedule();if(timer)clearInterval(timer);timer=setInterval(pump,20);pump()}
window.startBgm=start;
window.__BGM_V29__={start,version:'v29',master:()=>master};
})();