const c=document.getElementById('c'),ctx=c.getContext('2d');c.width=1100;c.height=720;const W=c.width,H=c.height;
const $=id=>document.getElementById(id),ui={score:$('score'),turn:$('turn'),miss:$('miss'),pf:$('pf'),af:$('af'),pv:$('pv'),av:$('av'),msg:$('centerMsg'),bubble:$('galBubble'),icon:$('galIcon'),cutin:$('cutin'),cutinImg:$('cutinImg'),cutinText:$('cutinText'),log:$('log'),go:$('gameover'),goTitle:$('goTitle'),goText:$('goText')};
$('galFull').src=GAL_IMGS.full;ui.icon.src=GAL_IMGS.normal;ui.cutinImg.src=GAL_IMGS.joy;
const voices=[['イェイ','https://amitaro.net/download/voice/401_ainote/yeah_01.wav'],['イェァー！','https://amitaro.net/download/voice/401_ainote/yeah_03.wav'],['ナイス♪','https://amitaro.net/download/voice/401_ainote/nice_01.wav'],['ナイス','https://amitaro.net/download/voice/401_ainote/nice_02.wav'],['やった♪','https://amitaro.net/download/voice/103_yorokobu/yatta_01.wav'],['やりぃ♪','https://amitaro.net/download/voice/103_yorokobu/yarii_01.wav'],['すごい！','https://amitaro.net/download/voice/111_ganbaru/sugoi_01.wav'],['さっすがぁ！','https://amitaro.net/download/voice/111_ganbaru/sassugaa_02.wav']];let recent=[];
let pins=[],score=0,misses=0,turn=1,phase=0,meter=0,dir=1,power=0,accuracy=.5,raf=0,busy=false,aim={x:550,y:330},projectile=null;
function setGal(e,t){ui.icon.src=GAL_IMGS[e]||GAL_IMGS.normal;if(t)ui.bubble.textContent=t}
function flash(t,ms=650){ui.msg.textContent=t;ui.msg.classList.add('show');setTimeout(()=>ui.msg.classList.remove('show'),ms)}
function cutin(k,l,e='joy',ms=850){ui.cutin.className=k+' show';ui.cutinText.textContent=l;ui.cutinImg.src=GAL_IMGS[e]||GAL_IMGS.joy;setTimeout(()=>ui.cutin.className='',ms)}
function lg(t){ui.log.textContent=(t+'\n'+ui.log.textContent).slice(0,900)}
function voice(d=0){setTimeout(()=>{let p=voices.map((_,i)=>i).filter(i=>!recent.includes(i));if(!p.length)p=voices.map((_,i)=>i);let i=p[Math.floor(Math.random()*p.length)];recent.push(i);while(recent.length>2)recent.shift();let a=new Audio(voices[i][1]);a.volume=.82;a.playbackRate=.98+Math.random()*.04;a.play().catch(()=>{})},d)}
let ac=null,bgmTimer=null,bgmStep=0;function AC(){if(!ac)ac=new(AudioContext||webkitAudioContext)();if(ac.state==='suspended')ac.resume();return ac}
function tone(f,t,d,type='square',v=.02){let A=AC(),o=A.createOscillator(),g=A.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(A.destination);o.start(t);o.stop(t+d+.02)}
function noise(d=.04,v=.035,b=1900){let A=AC(),B=A.createBuffer(1,A.sampleRate*d,A.sampleRate),q=B.getChannelData(0);for(let i=0;i<q.length;i++)q[i]=(Math.random()*2-1)*(1-i/q.length);let s=A.createBufferSource(),bp=A.createBiquadFilter(),g=A.createGain();s.buffer=B;bp.type='bandpass';bp.frequency.value=b;g.gain.value=v;s.connect(bp).connect(g).connect(A.destination);s.start()}
function wood(s=1,p=1){let A=AC(),t=A.currentTime;[680,1040,1580].forEach((f,i)=>tone(f*p,t+i*.006,.045-i*.004,i?'square':'triangle',.04*s/(i+1)));noise(.035,.055*s,1800*p)}
function whoosh(){let A=AC(),t=A.currentTime;tone(155,t,.14,'sawtooth',.028);tone(300,t+.025,.1,'triangle',.016);noise(.09,.018,900)}function land(){let A=AC(),t=A.currentTime;tone(125,t,.07,'triangle',.027);noise(.035,.022,650)}
function startBgm(){if(bgmTimer)return;AC();let m=[587,659,698,784,698,659,587,523,587,659,698,784,880,784,698,659];bgmTimer=setInterval(()=>{let A=AC(),t=A.currentTime+.01,b=bgmStep%4;if(b===0||b===2){tone(82,t,.11,'triangle',.024);tone(55,t,.07,'sine',.027)}else{tone(205,t,.065,'square',.011);tone(330,t,.055,'triangle',.008)}if(bgmStep%2===0)tone(m[(bgmStep/2)%m.length],t,.09,'square',.009);bgmStep++},180)}
function officialSetup(){pins=[];let r=[[[1,-36],[2,36]],[[3,-72],[10,0],[4,72]],[[5,-108],[11,-36],[12,36],[6,108]],[[7,-72],[9,0],[8,72]]];r.forEach((row,ri)=>row.forEach(([n,dx])=>pins.push({n,x:550+dx,y:425-ri*60,state:'standing',rot:0,lean:0})))}
function resetGame(){officialSetup();score=0;misses=0;turn=1;phase=0;meter=0;busy=false;projectile=null;ui.go.classList.remove('show');ui.pf.style.width=ui.af.style.width='0';ui.pv.textContent=ui.av.textContent='0';setGal('normal','ぶっ倒してこー！');update();draw()}
function update(){ui.score.textContent=score;ui.turn.textContent='TURN '+turn;ui.miss.textContent='MISS × '+misses}function proj(px,py){let k=.72+py/920;return{x:px+(py-360)*.055,y:90+py*.77,k}}
function bg(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#53b6ef');g.addColorStop(.28,'#bde8ff');g.addColorStop(.281,'#1a67b0');g.addColorStop(.36,'#16477e');g.addColorStop(.361,'#9d814b');g.addColorStop(1,'#6c5230');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#214e7f';ctx.fillRect(0,190,W,80);ctx.fillStyle='#ccefff';for(let i=0;i<14;i++){let x=i*90+(i%2)*20,h=35+(i%5)*14;ctx.fillRect(x,150-h,44,h)}ctx.fillStyle='#0c4473';ctx.fillRect(0,242,W,9);for(let i=0;i<45;i++){let x=10+i*25,y=280+(i%3)*6;ctx.fillStyle=i%2?'#1b1831':'#2c2037';ctx.beginPath();ctx.arc(x,y-18,6,0,6.28);ctx.fill();ctx.fillRect(x-6,y-13,12,23)}ctx.fillStyle='#cf2f6c';ctx.fillRect(330,200,440,52);ctx.strokeStyle='#ffe277';ctx.lineWidth=4;ctx.strokeRect(330,200,440,52);ctx.fillStyle='#fff29c';ctx.font='1000 31px Arial';ctx.textAlign='center';ctx.fillText('MÖLKKY GAL CHAMPIONSHIP',550,235);ctx.strokeStyle='rgba(255,255,255,.12)';for(let y=340;y<665;y+=52){ctx.beginPath();ctx.moveTo(120,y);ctx.lineTo(980,y);ctx.stroke()}}
function pin(p){let s=proj(p.x,p.y);ctx.save();ctx.translate(s.x,s.y);ctx.rotate(p.state==='leaning'?p.lean:p.rot);ctx.scale(s.k,s.k);ctx.fillStyle='#cc9e58';ctx.strokeStyle='#5e3916';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-18,-40,36,82,8);ctx.fill();ctx.stroke();ctx.fillStyle='#efd18b';ctx.beginPath();ctx.ellipse(0,-34,17,8,-.1,0,6.28);ctx.fill();ctx.fillStyle='#1c160e';ctx.font='1000 20px Arial';ctx.textAlign='center';ctx.fillText(p.n,0,-27);ctx.restore()}
function draw(){bg();let a=proj(aim.x,aim.y);ctx.strokeStyle='#ffe04f';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(a.x,a.y,22,13,0,0,6.28);ctx.stroke();pins.slice().sort((a,b)=>a.y-b.y).forEach(pin);if(projectile){let t=projectile.t,x=projectile.a.x+(projectile.b.x-projectile.a.x)*t,y=projectile.a.y+(projectile.b.y-projectile.a.y)*t-Math.sin(Math.PI*t)*projectile.arc,s=proj(x,y);ctx.fillStyle='#c99b56';ctx.fillRect(s.x-24,s.y-8,48,16)}}
function ml(){cancelAnimationFrame(raf);meter=0;dir=1;let f=()=>{meter+=dir*.018;if(meter>=1){meter=1;dir=-1}if(meter<=0){meter=0;dir=1}if(phase===1){ui.pf.style.width=meter*100+'%';ui.pv.textContent=Math.round(meter*100)}if(phase===2){ui.af.style.width=meter*100+'%';ui.av.textContent=Math.round(meter*100)}raf=requestAnimationFrame(f)};f()}
function action(){if(busy)return;AC();startBgm();if(phase===0){phase=1;flash('POWER');ml();return}if(phase===1){power=meter;phase=2;flash('ACCURACY');ml();return}if(phase===2){accuracy=meter;cancelAnimationFrame(raf);launch()}}
function launch(){busy=true;phase=3;whoosh();flash('THROW!');let q=1-Math.abs(accuracy-.5)*2,e=(1-q)*(24+power*58),a=Math.random()*6.28,ix=aim.x+Math.cos(a)*e,iy=aim.y+Math.sin(a)*e;projectile={a:{x:550,y:720},b:{x:ix,y:iy},t:0,arc:90+power*115};let st=performance.now();function f(n){projectile.t=Math.min(1,(n-st)/520);draw();if(projectile.t<1)requestAnimationFrame(f);else{projectile=null;impact(ix,iy)}}requestAnimationFrame(f)}
function impact(ix,iy){let S=pins.filter(p=>p.state!=='fallen'),C=S.map(p=>({p,d:Math.hypot(p.x-ix,p.y-iy)})).sort((a,b)=>a.d-b.d),hit=[];if(C[0]&&C[0].d<24+power*32)hit=[C[0].p];if(!hit.length){resolve([],[],ix,iy);return}wood(1.25);let seen=new Set(hit),q=[...hit],levels=new Map(hit.map(p=>[p,0]));while(q.length){let s=q.shift(),lv=levels.get(s),near=S.filter(p=>!seen.has(p)&&Math.hypot(p.x-s.x,p.y-s.y)<41+power*20).slice(0,power>.72?2:1);for(let p of near)if(Math.random()<.42+power*.38){seen.add(p);hit.push(p);levels.set(p,lv+1);q.push(p)}}let f=[],l=[];hit.forEach(p=>(Math.random()<.70+power*.24-(levels.get(p)||0)*.07?f:l).push(p));resolve(f,l,ix,iy,levels)}
function resolve(f,l,ix,iy,L=new Map()){if(!f.length){misses++;setGal(misses===2?'thinking':'regret',misses===2?'それ外したらヤバくない？集中〜！':'あー……惜しー！');flash('MISS!!');if(misses===2)cutin('danger','3投目ミス危機','thinking');if(misses>=3){cutin('loss','DISQUALIFIED','regret',1200);setTimeout(()=>end('DISQUALIFIED','3投連続0本で失格'),700)}finish();return}misses=0;f.forEach((p,i)=>setTimeout(()=>{p.state='fallen';p.rot=(Math.random()>.5?1:-1)*1.35;wood(.72);land();voice(80);draw()},(L.get(p)||0)*85+i*15));l.forEach(p=>{p.state='leaning';p.lean=(Math.random()>.5?1:-1)*.48});let pts=f.length===1?f[0].n:f.length;score+=pts;if(f.length===1){setGal('normal','ナイスー！');if(pts>=8)cutin('long','LONG SHOT!!','surprise')}else if(f.length>=4){setGal('joy','お、巻き込んだ！いいじゃん！');cutin('smash','SMASH!!','joy')}else{setGal('joy','お、巻き込んだ！いいじゃん！');cutin('chain','CHAIN!!','joy')}flash('+'+pts+' POINT');lg('FALLEN '+f.map(p=>p.n)+' +'+pts);if(score>50){score=25;cutin('danger','OVER 50 → 25','thinking');setGal('thinking','欲張ったー！25点戻し！')}update();if(score===50){cutin('win','PERFECT 50!!','joy',1400);setGal('joy','うっま！！！最高ー！！');voice(120);setTimeout(()=>end('PERFECT 50!','50点ジャスト！'),850);return}setTimeout(()=>{f.forEach(p=>{let dx=p.x-ix,dy=p.y-iy,n=Math.hypot(dx,dy)||1,d=20+power*46+Math.random()*18;p.x=Math.max(75,Math.min(1025,p.x+dx/n*d));p.y=Math.max(150,Math.min(595,p.y+dy/n*d));p.state='standing';p.rot=0});finish()},1100)}
function finish(){turn++;phase=0;meter=0;ui.pf.style.width=ui.af.style.width='0';ui.pv.textContent=ui.av.textContent='0';busy=false;update();draw()}function end(t,x){busy=true;ui.goTitle.textContent=t;ui.goText.textContent=x;ui.go.classList.add('show')}
c.addEventListener('mousemove',e=>{if(phase||busy)return;let r=c.getBoundingClientRect();aim.x=(e.clientX-r.left)*W/r.width;aim.y=(e.clientY-r.top)*H/r.height;draw()});c.addEventListener('click',action);addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();action()}});resetGame();