const c=document.getElementById('c'),ctx=c.getContext('2d');c.width=1100;c.height=720;const W=c.width,H=c.height;
const $=id=>document.getElementById(id),ui={score:$('score'),turn:$('turn'),miss:$('miss'),pf:$('pf'),af:$('af'),pv:$('pv'),av:$('av'),msg:$('centerMsg'),bubble:$('galBubble'),icon:$('galIcon'),cutin:$('cutin'),cutinImg:$('cutinImg'),cutinText:$('cutinText'),log:$('log'),go:$('gameover'),goTitle:$('goTitle'),goText:$('goText')};
let pins=[],score=0,misses=0,turn=1,phase=0,meter=0,dir=1,power=0,accuracy=.5,raf=0,busy=false,aim={x:550,y:330},projectile=null;
const OFFICIAL_FIELD=Object.freeze({initialDistanceM:3.5,initialPinY:425,molkkaariY:690,throwOriginY:720,worldUnitsPerMetre:(690-425)/3.5,molkkaariDrawWidth:156,molkkaariDrawHeight:68});
const PIN_RENDER=Object.freeze({sourceWidth:72,sourceHeight:144,width:56,height:112,top:-70,shadowY:40});
const pinSprites=Array.from({length:13},(_,n)=>{if(!n)return null;let img=new Image();img.decoding='async';img.onload=()=>draw();img.src=`objects/skittles/official90s/images/pin_${String(n).padStart(2,'0')}.webp?v=31`;return img});
const molkkaariSprite=new Image();molkkaariSprite.decoding='async';molkkaariSprite.onload=()=>draw();molkkaariSprite.src='objects/field/official/images/molkkaari.webp?v=31';
function setGal(e,t){return PresentationRuntime.setGal(e,t)}
function flash(t,ms=650){ui.msg.textContent=t;ui.msg.classList.add('show');setTimeout(()=>ui.msg.classList.remove('show'),ms)}
function cutin(k,l,e='joy',ms=850){return PresentationRuntime.cutin(k,l,e,ms)}
function lg(t){ui.log.textContent=(t+'\n'+ui.log.textContent).slice(0,900)}
function officialSetup(){pins=[];let r=[[[1,-36],[2,36]],[[3,-72],[10,0],[4,72]],[[5,-108],[11,-36],[12,36],[6,108]],[[7,-72],[9,0],[8,72]]];r.forEach((row,ri)=>row.forEach(([n,dx])=>pins.push({n,x:550+dx,y:OFFICIAL_FIELD.initialPinY-ri*60,state:'standing',rot:0,lean:0})))}
function resetGame(){officialSetup();score=0;misses=0;turn=1;phase=0;meter=0;busy=false;projectile=null;ui.go.classList.remove('show');ui.pf.style.width=ui.af.style.width='0';ui.pv.textContent=ui.av.textContent='0';setGal('normal','ぶっ倒してこー！');update();draw()}
function update(){ui.score.textContent=score;ui.turn.textContent='TURN '+turn;ui.miss.textContent='MISS × '+misses}
function proj(px,py){let k=.72+py/920;return{x:px+(py-360)*.055,y:90+py*.77,k}}
function drawMolkkaari(){let s=proj(550,OFFICIAL_FIELD.molkkaariY),w=OFFICIAL_FIELD.molkkaariDrawWidth,h=OFFICIAL_FIELD.molkkaariDrawHeight;ctx.save();ctx.translate(s.x,s.y);ctx.scale(s.k,s.k);ctx.imageSmoothingEnabled=false;ctx.fillStyle='rgba(31,20,11,.28)';ctx.beginPath();ctx.ellipse(0,h*.36,w*.51,h*.13,0,0,6.28);ctx.fill();if(molkkaariSprite.complete&&molkkaariSprite.naturalWidth)ctx.drawImage(molkkaariSprite,-w/2,-h/2,w,h);ctx.restore()}
function pin(p){let s=proj(p.x,p.y),img=pinSprites[p.n],r=PIN_RENDER;ctx.save();ctx.translate(s.x,s.y);ctx.scale(s.k,s.k);ctx.fillStyle='rgba(31,20,11,.4)';ctx.beginPath();ctx.ellipse(0,r.shadowY,23,5,0,0,6.28);ctx.fill();ctx.rotate(p.state==='leaning'?p.lean:p.rot);ctx.imageSmoothingEnabled=false;if(img&&img.complete&&img.naturalWidth)ctx.drawImage(img,0,0,r.sourceWidth,r.sourceHeight,-r.width/2,r.top,r.width,r.height);else{ctx.fillStyle='#c98f43';ctx.strokeStyle='#5e3916';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-26,-42);ctx.lineTo(7,-70);ctx.lineTo(26,-53);ctx.lineTo(26,42);ctx.lineTo(-26,42);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#efd18b';ctx.beginPath();ctx.ellipse(0,-52,28,13,-.52,0,6.28);ctx.fill();ctx.fillStyle='#54270f';ctx.font='1000 20px monospace';ctx.textAlign='center';ctx.fillText(p.n,0,-47)}ctx.restore()}
function draw(){StageRuntime.draw(ctx,W,H);drawMolkkaari();let a=proj(aim.x,aim.y);ctx.strokeStyle='#ffe04f';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(a.x,a.y,22,13,0,0,6.28);ctx.stroke();pins.slice().sort((a,b)=>a.y-b.y).forEach(pin);if(projectile){let t=projectile.t,x=projectile.a.x+(projectile.b.x-projectile.a.x)*t,y=projectile.a.y+(projectile.b.y-projectile.a.y)*t-Math.sin(Math.PI*t)*projectile.arc,s=proj(x,y);ctx.fillStyle='#c99b56';ctx.fillRect(s.x-24,s.y-8,48,16)}}
function ml(){cancelAnimationFrame(raf);meter=0;dir=1;let f=()=>{meter+=dir*.018;if(meter>=1){meter=1;dir=-1}if(meter<=0){meter=0;dir=1}if(phase===1){ui.pf.style.width=meter*100+'%';ui.pv.textContent=Math.round(meter*100)}if(phase===2){ui.af.style.width=meter*100+'%';ui.av.textContent=Math.round(meter*100)}raf=requestAnimationFrame(f)};f()}
function action(){if(busy)return;AudioManager.resume().catch(()=>{});AudioRuntime.startBgm();if(phase===0){phase=1;flash('POWER');ml();return}if(phase===1){power=meter;phase=2;flash('ACCURACY');ml();return}if(phase===2){accuracy=meter;cancelAnimationFrame(raf);launch()}}
function launch(){busy=true;phase=3;AudioRuntime.whoosh();flash('THROW!');let q=1-Math.abs(accuracy-.5)*2,e=(1-q)*(24+power*58),a=Math.random()*6.28,ix=aim.x+Math.cos(a)*e,iy=aim.y+Math.sin(a)*e;projectile={a:{x:550,y:OFFICIAL_FIELD.throwOriginY},b:{x:ix,y:iy},t:0,arc:90+power*115};let st=performance.now();function f(n){projectile.t=Math.min(1,(n-st)/520);draw();if(projectile.t<1)requestAnimationFrame(f);else{projectile=null;impact(ix,iy)}}requestAnimationFrame(f)}
function impact(ix,iy){let S=pins.filter(p=>p.state!=='fallen'),C=S.map(p=>({p,d:Math.hypot(p.x-ix,p.y-iy)})).sort((a,b)=>a.d-b.d),hit=[];if(C[0]&&C[0].d<24+power*32)hit=[C[0].p];if(!hit.length){resolve([],[],ix,iy);return}AudioRuntime.wood(1.25);let seen=new Set(hit),q=[...hit],levels=new Map(hit.map(p=>[p,0]));while(q.length){let s=q.shift(),lv=levels.get(s),near=S.filter(p=>!seen.has(p)&&Math.hypot(p.x-s.x,p.y-s.y)<41+power*20).slice(0,power>.72?2:1);for(let p of near)if(Math.random()<.42+power*.38){seen.add(p);hit.push(p);levels.set(p,lv+1);q.push(p)}}let f=[],l=[];hit.forEach(p=>(Math.random()<.70+power*.24-(levels.get(p)||0)*.07?f:l).push(p));resolve(f,l,ix,iy,levels)}
function resolve(f,l,ix,iy,L=new Map()){if(!f.length){misses++;setGal(misses===2?'thinking':'regret',misses===2?'それ外したらヤバくない？集中〜！':'あー……惜しー！');flash('MISS!!');if(misses===2)cutin('danger','3投目ミス危機','thinking');if(misses>=3){cutin('loss','DISQUALIFIED','regret',1200);setTimeout(()=>end('DISQUALIFIED','3投連続0本で失格'),700)}finish();return}misses=0;f.forEach((p,i)=>setTimeout(()=>{p.state='fallen';p.rot=(Math.random()>.5?1:-1)*1.35;AudioRuntime.wood(.72);AudioRuntime.land();AudioRuntime.voice(80);draw()},(L.get(p)||0)*85+i*15));l.forEach(p=>{p.state='leaning';p.lean=(Math.random()>.5?1:-1)*.48});let pts=f.length===1?f[0].n:f.length;score+=pts;if(f.length===1){setGal('normal','ナイスー！');if(pts>=8)cutin('long','LONG SHOT!!','surprise')}else if(f.length>=4){setGal('joy','お、巻き込んだ！いいじゃん！');cutin('smash','SMASH!!','joy')}else{setGal('joy','お、巻き込んだ！いいじゃん！');cutin('chain','CHAIN!!','joy')}flash('+'+pts+' POINT');lg('FALLEN '+f.map(p=>p.n)+' +'+pts);if(score>50){score=25;cutin('danger','OVER 50 → 25','thinking');setGal('thinking','欲張ったー！25点戻し！')}update();if(score===50){cutin('win','PERFECT 50!!','joy',1400);setGal('joy','うっま！！！最高ー！！');AudioRuntime.voice(120);setTimeout(()=>end('PERFECT 50!','50点ジャスト！'),850);return}setTimeout(()=>{f.forEach(p=>{let dx=p.x-ix,dy=p.y-iy,n=Math.hypot(dx,dy)||1,d=20+power*46+Math.random()*18;p.x=Math.max(75,Math.min(1025,p.x+dx/n*d));p.y=Math.max(150,Math.min(595,p.y+dy/n*d));p.state='standing';p.rot=0});finish()},1100)}
function finish(){turn++;phase=0;meter=0;ui.pf.style.width=ui.af.style.width='0';ui.pv.textContent=ui.av.textContent='0';busy=false;update();draw()}
function end(t,x){busy=true;ui.goTitle.textContent=t;ui.goText.textContent=x;ui.go.classList.add('show')}
c.addEventListener('mousemove',e=>{if(phase||busy)return;let r=c.getBoundingClientRect();aim.x=(e.clientX-r.left)*W/r.width;aim.y=(e.clientY-r.top)*H/r.height;draw()});c.addEventListener('click',action);addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();action()}});window.resetGame=resetGame;resetGame();
