(function(){'use strict';
var game=document.getElementById('game'),base=document.getElementById('c'),impact=document.getElementById('impactFx');
if(!game||!base||!impact)return;
var layer=document.createElement('canvas');layer.id='mangaFx';layer.width=1100;layer.height=720;game.appendChild(layer);
var g=layer.getContext('2d'),fx=[],raf=0,lastLog='',reduced=matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches,TAU=Math.PI*2;
function now(){return performance.now()}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function ease(t){return 1-Math.pow(1-t,4)}
function add(kind,data,duration,delay){fx.push(Object.assign({kind:kind,start:now()+(delay||0),duration:duration},data||{}));run()}
function run(){if(!raf)raf=requestAnimationFrame(frame)}
function frame(t){raf=0;g.clearRect(0,0,1100,720);fx=fx.filter(function(e){var p=(t-e.start)/e.duration;if(p<0)return true;if(p>=1)return false;draw(e,clamp(p,0,1));return true});if(fx.length)raf=requestAnimationFrame(frame)}
function line(x1,y1,x2,y2,w,color,a){g.globalAlpha=a;g.strokeStyle=color;g.lineWidth=w;g.beginPath();g.moveTo(x1,y1);g.lineTo(x2,y2);g.stroke();g.globalAlpha=1}
function polygon(cx,cy,r,n,spin,color,a){g.save();g.translate(cx,cy);g.rotate(spin);g.fillStyle=color;g.globalAlpha=a;g.beginPath();for(var i=0;i<n*2;i++){var q=i/(n*2)*TAU,rr=i%2?r*.48:r;g.lineTo(Math.cos(q)*rr,Math.sin(q)*rr)}g.closePath();g.fill();g.restore();g.globalAlpha=1}
function rays(e,p){var grow=ease(p),fade=1-Math.max(0,(p-.54)/.46);g.save();g.translate(e.x,e.y);g.rotate(e.spin+p*.08);for(var i=0;i<e.count;i++){var a=i/e.count*TAU+(i%4)*.012,r1=(35+(i%7)*9)*grow,r2=(530+(i%9)*35)*grow,w=(i%6===0?34:i%3===0?16:7)*(1-p*.35),c=i%5===0?'#ff2b82':i%2?'#13091e':'#fff04a';line(Math.cos(a)*r1,Math.sin(a)*r1,Math.cos(a)*r2,Math.sin(a)*r2,w,c,fade*(i%2?.86:.68))}g.restore()}
function bolt(e,p){var pts=[],dx=e.b.x-e.a.x,dy=e.b.y-e.a.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,steps=8;for(var i=0;i<=steps;i++){var q=i/steps,j=i===0||i===steps?0:Math.sin(e.seed*19+i*11.3)*e.jitter*(1-p*.5);pts.push({x:e.a.x+dx*q+nx*j,y:e.a.y+dy*q+ny*j})}g.save();g.lineJoin='miter';g.lineCap='square';for(var k=0;k<3;k++){g.beginPath();g.moveTo(pts[0].x,pts[0].y);for(i=1;i<pts.length;i++)g.lineTo(pts[i].x,pts[i].y);g.strokeStyle=k===0?'#16061c':k===1?'#ff2d88':'#fff9ae';g.lineWidth=k===0?24:k===1?13:4;g.globalAlpha=(1-p)*(k===0?.85:1);g.stroke()}g.restore();g.globalAlpha=1}
function stamp(e,p){var appear=Math.min(1,p*8),fade=1-Math.max(0,(p-.7)/.3),s=(.25+ease(Math.min(1,p*2.4))*.75)*(e.scale||1);g.save();g.translate(e.x,e.y-p*34);g.rotate(e.angle||-.1);g.scale(s,s);g.textAlign='center';g.textBaseline='middle';g.lineJoin='round';g.globalAlpha=appear*fade;g.font='1000 '+(e.size||104)+'px Impact,Arial Black,sans-serif';g.strokeStyle='#090211';g.lineWidth=30;g.strokeText(e.text,0,0);g.strokeStyle=e.edge||'#8b23df';g.lineWidth=17;g.strokeText(e.text,0,0);g.fillStyle=e.fill||'#fff23d';g.fillText(e.text,0,0);if(e.sub){g.font='1000 26px Arial Black,sans-serif';g.strokeStyle='#090211';g.lineWidth=10;g.strokeText(e.sub,0,(e.size||104)*.7);g.fillStyle='#fff';g.fillText(e.sub,0,(e.size||104)*.7)}g.restore();g.globalAlpha=1}
function shock(e,p){g.save();g.translate(e.x,e.y);g.rotate(e.angle||-.08);g.globalAlpha=(1-p)*.95;g.strokeStyle=e.color||'#fff34b';g.lineWidth=22*(1-p)+3;g.shadowColor=e.color||'#fff34b';g.shadowBlur=28;g.beginPath();g.ellipse(0,0,(20+e.w*ease(p)),(8+e.h*ease(p)),0,0,TAU);g.stroke();g.shadowBlur=0;g.strokeStyle='#fff';g.lineWidth=7*(1-p)+2;g.stroke();g.restore();g.globalAlpha=1}
function shards(e,p){g.save();g.translate(e.x,e.y);for(var i=0;i<e.count;i++){var a=(i*2.399+e.seed)%TAU,d=(40+(i%7)*22)*ease(p),s=(18+(i%5)*7)*(1-p*.5);g.save();g.translate(Math.cos(a)*d,Math.sin(a)*d);g.rotate(a+p*5*(i%2?1:-1));g.fillStyle=i%3===0?'#25eaff':i%2?'#ffef42':'#ff2b82';g.globalAlpha=1-p;g.beginPath();g.moveTo(s,0);g.lineTo(-s*.45,s*.26);g.lineTo(-s*.2,-s*.2);g.closePath();g.fill();g.restore()}g.restore();g.globalAlpha=1}
function speed(e,p){var fade=(1-p)*.72;g.save();g.translate(e.x,e.y);for(var i=0;i<e.count;i++){var y=((i*73+e.seed*31)%720)-360,x=-620+p*1240+(i%5)*70,w=160+(i%7)*58;line(x,y,x+w,y-(i%3-1)*12,i%4===0?15:5,i%3===0?'#ffea35':'#fff',fade)}g.restore()}
function draw(e,p){
  if(e.kind==='flash'){g.fillStyle=e.color;g.globalAlpha=(1-p)*e.alpha;g.fillRect(0,0,1100,720);g.globalAlpha=1;return}
  if(e.kind==='rays'){rays(e,p);return}if(e.kind==='bolt'){bolt(e,p);return}if(e.kind==='stamp'){stamp(e,p);return}if(e.kind==='shock'){shock(e,p);return}if(e.kind==='shards'){shards(e,p);return}if(e.kind==='speed'){speed(e,p);return}
  if(e.kind==='menace'){g.save();g.textAlign='center';g.font='1000 64px Impact,Arial Black,sans-serif';g.fillStyle='#bb45ff';g.strokeStyle='#17051d';g.lineWidth=14;g.globalAlpha=(1-p)*(.75+.25*Math.sin(p*40));g.strokeText('ゴ ゴ ゴ ゴ ゴ…',e.x,e.y-p*18);g.fillText('ゴ ゴ ゴ ゴ ゴ…',e.x,e.y-p*18);g.restore();g.globalAlpha=1}
}
function kickClass(cls,ms){game.classList.remove('manga-lock','manga-overdrive','manga-crush');void game.offsetWidth;game.classList.add(cls);setTimeout(function(){game.classList.remove(cls)},ms)}
function sound(){return window.MangaImpactAudio||null}
function syncAudioState(){var s=sound();layer.dataset.audio=s&&s.state?s.state():'unavailable'}
function targetPoint(){var raw=(impact.dataset.targetAim||'').split(',').map(Number);if(raw.length<2||!isFinite(raw[0])||!isFinite(raw[1]))return{x:550,y:390};try{return proj(raw[0],raw[1])}catch(e){return{x:550,y:390}}}
function targetLocked(){if(!impact.dataset.targetLocked)return;var p=targetPoint();layer.dataset.last='lock';layer.dataset.locked=impact.dataset.targetLocked;add('flash',{color:'#39efff',alpha:.24},130);add('rays',{x:p.x,y:p.y,count:reduced?18:46,spin:.12},430);add('shock',{x:p.x,y:p.y,w:155,h:62,color:'#2eeaff'},460);add('menace',{x:clamp(p.x,250,850),y:clamp(p.y-120,130,560)},680);add('stamp',{x:clamp(p.x,210,890),y:clamp(p.y-75,150,565),text:'LOCK ON!',sub:'TARGET '+impact.dataset.targetLocked,size:72,scale:.72,fill:'#fff04a',edge:'#13cfea'},520);kickClass('manga-lock',280);var s=sound();if(s&&s.ping)s.ping();syncAudioState()}
function throwFx(){layer.dataset.last='throw';add('flash',{color:'#fff9bd',alpha:.48},100);add('speed',{x:550,y:360,count:reduced?12:34,seed:7},520);add('stamp',{x:550,y:250,text:'いっけぇぇ!!',sub:'FULL POWER THROW',size:88,fill:'#fff34c',edge:'#ff2d82'},620);add('rays',{x:550,y:510,count:reduced?16:38,spin:-.2},480)}
function missFx(){layer.dataset.last='miss';add('flash',{color:'#5a7bb9',alpha:.24},160);add('stamp',{x:550,y:330,text:'ズコォ…',sub:'NO IMPACT',size:104,fill:'#dce9ff',edge:'#314e8f'},680)}
function scoreFx(ids){var list=[];try{list=pins.filter(function(p){return ids.indexOf(p.n)>=0})}catch(e){}var p={x:550,y:385};if(list.length){p={x:0,y:0};list.forEach(function(pin){var q=proj(pin.x,pin.y);p.x+=q.x;p.y+=q.y});p.x/=list.length;p.y/=list.length}var strong=ids.length>=3,text=ids.length>=4?'ドッッカァァン!!':ids.length>=2?'バギャギャァ!!':ids[0]>=8?'ズギャァァン!!':'ドゴォン!!';layer.dataset.last='score';layer.dataset.count=String((Number(layer.dataset.count)||0)+1);layer.dataset.fallen=ids.join(',');add('flash',{color:'#fff',alpha:.98},105);add('flash',{color:strong?'#ff174f':'#ffe52d',alpha:.55},260,65);add('rays',{x:p.x,y:p.y,count:reduced?24:strong?96:72,spin:-.17},strong?940:760);add('shock',{x:p.x,y:p.y,w:strong?470:330,h:strong?160:110,color:'#fff43c'},720);add('shock',{x:p.x,y:p.y,w:strong?350:250,h:strong?270:190,color:'#ff2d88',angle:.65},640,60);for(var i=0;i<(reduced?4:strong?15:10);i++){var a=i/(strong?15:10)*TAU+.15,b={x:p.x+Math.cos(a)*560,y:p.y+Math.sin(a)*420};add('bolt',{a:p,b:b,seed:i*.71+ids[0],jitter:strong?48:34},strong?650:510,i*12)}add('shards',{x:p.x,y:p.y,count:reduced?14:strong?62:42,seed:ids[0]*.37},820);add('stamp',{x:clamp(p.x,255,845),y:clamp(p.y-40,210,515),text:text,sub:strong?'MEGA CHAIN IMPACT!!':'WOODEN IMPACT!!',size:strong?128:112,scale:strong?1.12:1,fill:'#fff23a',edge:strong?'#ff174f':'#8a22d5',angle:ids.length%2?.09:-.11},strong?1280:980,55);kickClass(strong?'manga-crush':'manga-overdrive',strong?720:520);var s=sound();if(s&&s.boom)s.boom(strong);syncAudioState()}
new MutationObserver(function(ms){if(ms.some(function(m){return m.attributeName==='data-target-locked'}))targetLocked()}).observe(impact,{attributes:true,attributeFilter:['data-target-locked']});
var center=document.getElementById('centerMsg');if(center)new MutationObserver(function(){var t=center.textContent||'';if(t==='THROW!')throwFx();else if(t==='MISS!!')missFx()}).observe(center,{childList:true,characterData:true,subtree:true});
var log=document.getElementById('log');if(log)new MutationObserver(function(){var first=(log.textContent||'').split('\n')[0];if(first===lastLog)return;lastLog=first;var m=first.match(/^FALLEN ([0-9,]+) \+/);if(m)scoreFx(m[1].split(',').map(Number))}).observe(log,{childList:true,characterData:true,subtree:true});
layer.dataset.ready='true';syncAudioState();window.MangaOverdrive={layer:layer,score:scoreFx,throwFx:throwFx};
})();
