(()=>{
'use strict';
const BPM=172, QUARTER=60/BPM, EIGHTH=QUARTER/2;
const OAC=window.OfflineAudioContext||window.webkitOfflineAudioContext;
let player=null, blobUrl=null, preparing=null, wanted=false;
const SEMI={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,F:5,'F#':6,Gb:6,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11};
function hz(note){const m=note.match(/^([A-G])([#b]?)(\d)$/),key=m[1]+m[2],oct=+m[3],midi=12*(oct+1)+SEMI[key];return 440*Math.pow(2,(midi-69)/12)}
const A=[['A4',1.5],['D5',.5],['D5',1],['E5',1],['F5',1],['D5',1],['D5',1],['F5',1],['E5',1],['C5',1],['C5',1],['E5',1],['F5',.5],['E5',.5],['D5',.5],['C5',.5],['D5',1],['A4',1],['D5',1.5],['D5',.5],['D5',1],['E5',1],['F5',1],['D5',1],['D5',2],['G5',.5],['A5',.5],['G5',.5],['F5',.5],['E5',1],['D5',1],['F5',1],['D5',1],['D5',2]];
const B=[['A5',1],['A5',1],['G5',1],['F5',1],['E5',1],['C5',1],['C5',1],['E5',1],['G5',1],['G5',1],['F5',1],['E5',1],['F5',1],['D5',1],['D5',1],['F5',1],['A5',1],['A5',1],['G5',1],['F5',1],['E5',1],['C5',1],['C5',1],['E5',1],['G5',1],['G5',1],['F5',1],['E5',1],['F5',1],['D5',1],['D5',2]];
const D=[['A5',1.5],['F5',.5],['F5',1],['A5',1],['G5',1],['E5',1],['E5',1],['F5',1],['G5',.5],['A5',.5],['G5',.5],['F5',.5],['E5',1],['D5',1],['D5',1],['E5',1],['F5',1],['G5',1],['A5',1.5],['F5',.5],['F5',1],['A5',1],['G5',1],['E5',1],['E5',1],['F5',1],['G5',.5],['A5',.5],['G5',.5],['F5',.5],['E5',1],['D5',1],['F5',1],['D5',1],['D5',2]];
const repeat=s=>s.concat(s), melody=[...repeat(A),...repeat(B),...repeat(A),...repeat(D)];
const progression=['D2','D2','C2','D2','D2','D2','A2','D2','D2','C2','C2','D2','D2','C2','A2','D2'];
let totalUnits=0;const events=melody.map(x=>{const e={note:x[0],units:x[1],start:totalUnits};totalUnits+=x[1];return e});
function env(c,t,a,d,v,dest){const g=c.createGain();g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(v,.0002),t+a);g.gain.exponentialRampToValueAtTime(.0001,Math.min(t+a+d,c.length/c.sampleRate-.001));g.connect(dest);return g}
function wave(c,note,t,dur,type,vol,oct,cut,dest){const o=c.createOscillator(),lp=c.createBiquadFilter(),g=env(c,t,.004,dur,vol,dest);o.type=type;o.frequency.value=hz(note)*(oct||1);lp.type='lowpass';lp.frequency.value=cut||5000;o.connect(lp).connect(g);o.start(t);o.stop(Math.min(t+dur+.03,c.length/c.sampleRate-.001))}
function kick(c,t,dest,strong){const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(145,t);o.frequency.exponentialRampToValueAtTime(43,t+.075);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.58*strong,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+.21);o.connect(g).connect(dest);o.start(t);o.stop(t+.23)}
function bass(c,note,t,dest,strong){wave(c,note,t,.26,'sine',.42*strong,1,280,dest);wave(c,note,t,.20,'triangle',.17*strong,2,680,dest);wave(c,note,t,.12,'square',.04*strong,2,980,dest);wave(c,note,t,.15,'sine',.10*strong,.5,180,dest)}
function noise(c,t,dur,vol,freq,dest){const len=Math.max(1,Math.floor(c.sampleRate*dur)),b=c.createBuffer(1,len,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<len;i++)a[i]=(Math.random()*2-1)*Math.exp(-i/(len*.22));const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=freq;f.Q.value=.9;g.gain.value=vol;s.connect(f).connect(g).connect(dest);s.start(t)}
function chank(c,t,dest,strong){noise(c,t,.055,.12*strong,1550,dest)}
function snare(c,t,dest,strong){noise(c,t,.095,.060*strong,1900,dest)}
function hat(c,t,dest,strong){noise(c,t,.035,.020*strong,7400,dest)}
function brass(c,note,t,units,dest,accent){const dur=Math.max(.08,units*EIGHTH*.90),f=hz(note),bus=c.createGain(),lp=c.createBiquadFilter(),g=c.createGain();lp.type='lowpass';lp.frequency.value=2400;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.060*accent,t+.018);g.gain.exponentialRampToValueAtTime(.048*accent,t+dur*.55);g.gain.exponentialRampToValueAtTime(.0001,t+dur);[['sawtooth',f,-8,.60],['sawtooth',f,7,.45],['square',f*.5,2,.22],['triangle',f*2,-3,.20]].forEach(x=>{const o=c.createOscillator(),og=c.createGain();o.type=x[0];o.frequency.value=x[1];o.detune.value=x[2];og.gain.value=x[3];o.connect(og).connect(bus);o.start(t);o.stop(Math.min(t+dur+.03,c.length/c.sampleRate-.001))});bus.connect(lp).connect(g).connect(dest)}
function renderLoop(){if(preparing)return preparing;if(!OAC)return Promise.reject(new Error('OfflineAudioContext unavailable'));const seconds=totalUnits*EIGHTH,sr=32000,c=new OAC(2,Math.ceil(seconds*sr),sr),master=c.createGain(),comp=c.createDynamicsCompressor();master.gain.value=.46;comp.threshold.value=-15;comp.knee.value=12;comp.ratio.value=7;comp.attack.value=.002;comp.release.value=.16;master.connect(comp).connect(c.destination);
for(let u=0;u<Math.ceil(totalUnits);u++){const t=u*EIGHTH,pos=u%4,bar=Math.floor(u/4),root=progression[bar%progression.length];if(pos===0){kick(c,t,master,1.38);bass(c,root,t,master,1.42)}if(pos===2){kick(c,t,master,1.24);bass(c,root,t,master,1.30)}if(pos===1){chank(c,t,master,1.28);snare(c,t,master,.48)}if(pos===3){chank(c,t,master,1.42);snare(c,t,master,.58)}hat(c,t,master,(pos===0||pos===2)?.72:.90)}
events.forEach((ev,i)=>brass(c,ev.note,ev.start*EIGHTH,ev.units,master,(i%16===0)?1.08:1));
preparing=c.startRendering().then(buffer=>{const wav=toWav(buffer),blob=new Blob([wav],{type:'audio/wav'});blobUrl=URL.createObjectURL(blob);player=new Audio(blobUrl);player.loop=true;player.preload='auto';player.volume=1;player.setAttribute('playsinline','');player.addEventListener('ended',()=>{if(wanted){player.currentTime=0;player.play().catch(()=>{})}});if(wanted)return player.play().catch(()=>{});}).catch(e=>{preparing=null;throw e});return preparing}
function toWav(buffer){const ch=buffer.numberOfChannels,len=buffer.length,bytes=44+len*ch*2,ab=new ArrayBuffer(bytes),v=new DataView(ab);let p=0;const s=x=>{for(let i=0;i<x.length;i++)v.setUint8(p++,x.charCodeAt(i))};s('RIFF');v.setUint32(p,bytes-8,true);p+=4;s('WAVEfmt ');v.setUint32(p,16,true);p+=4;v.setUint16(p,1,true);p+=2;v.setUint16(p,ch,true);p+=2;v.setUint32(p,buffer.sampleRate,true);p+=4;v.setUint32(p,buffer.sampleRate*ch*2,true);p+=4;v.setUint16(p,ch*2,true);p+=2;v.setUint16(p,16,true);p+=2;s('data');v.setUint32(p,len*ch*2,true);p+=4;const data=[];for(let c=0;c<ch;c++)data[c]=buffer.getChannelData(c);for(let i=0;i<len;i++)for(let c=0;c<ch;c++){let x=Math.max(-1,Math.min(1,data[c][i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return ab}
function start(){wanted=true;if(player){if(player.paused)player.play().catch(()=>{});return player}renderLoop().catch(e=>console.warn('BGM render failed',e));return null}
function stop(){wanted=false;if(player)player.pause()}
window.startBgm=start;window.__BGM_V29__={start,stop,version:'v29-loop',player:()=>player};
})();